### ISSUE TITLE
ERROR - The cards are not showing (no cards)

### ISSUE THREAD

**Issue by future2back** [thaithimyduyen/Poker-Telegram-Bot#1]
Hello @thaithimyduyen how are you? I m trying to test this project but faced some dificulties

Created a file token.txt with content:
`TOKEN="YOUR TOKEN"`
replacing YOUR TOKEN to my token eg:
`TOKEN="21321321dsadasds123113213"`
But got invalid token, so bypassed it on main.py

```
#!/usr/bin/env python3

from app.pokerbot import PokerBot



def main():
    token = "21321321dsadasds123113213"
    bot = PokerBot(token=token)
    bot.run()


if __name__ == "__main__":
    main()
```
then it started listening so after /ready command got this error:

`redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.`
Solved by installing redis-server

`sudo apt-get install redis-server`

After that game start working but cards are not sent by bot and getting "no cards".

Do you have any idea?

Thank you!!!

**Comment by thaithimyduyen** [comment]
Hello @future2back!

When all players are `/ready`, you should send `/start`.

Could you send me your telegram username and we test it together?

**Comment by future2back** [comment]
@thaithimyduyen thanks for replying its not showing user.
Could you please send me a message? @henriqueturl
